### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by daniskuvc**
Hi team.
I updated the README.md, please review the content.

Thank you

### CODE REVIEW

**Review by Rogerrenjifo — CHANGES_REQUESTED** [review]
Good job. Please Specifies which environment variables are necessary and which are optional.

**Comment by daniskuvc** [comment]
> Good job. Please Specifies which environment variables are necessary and which are optional.

I made the changes, please review again.

Thanks

**Review by DenisseC02 — APPROVED** [review]
Looks good for me

**Review by Rogerrenjifo — APPROVED** [review]
Good Job my friend. 👍

**Review by TelmaRF — APPROVED** [review]
Great job @daniskuvc, it looks good to me!

**Comment by daniskuvc** [comment]
Thank you "API con pastel" team

**Pull request merged**
